# Generated by Django 4.0.1 on 2022-03-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('rated', models.CharField(max_length=50)),
                ('released', models.CharField(max_length=10)),
                ('runtime', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=10)),
                ('writer', models.CharField(max_length=10)),
                ('actor', models.TextField()),
                ('plot', models.CharField(max_length=10)),
                ('poster', models.CharField(max_length=100)),
                ('iratings', models.CharField(max_length=10)),
                ('ivotes', models.CharField(max_length=10)),
            ],
        ),
    ]
