# Generated by Django 4.0.1 on 2022-03-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_data',
            name='actor',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movies_data',
            name='director',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movies_data',
            name='genre',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movies_data',
            name='iratings',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movies_data',
            name='ivotes',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movies_data',
            name='plot',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movies_data',
            name='poster',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies_data',
            name='rated',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movies_data',
            name='released',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movies_data',
            name='runtime',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movies_data',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movies_data',
            name='writer',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movies_data',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
